export const LOAD_MOVIES = 'app/LOAD_MOVIES';
export const LOAD_MOVIES_SUCCESS = 'app/LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_ERROR = 'app/LOAD_MOVIES_ERROR';



export const UPDATE_LIST= 'app/UPDATE_LIST';
export const UPDATE_LIST_SUCCESS = 'app/UPDATE_LIST_SUCCESS';
export const UPDATE_LIST_ERROR = 'app/UPDATE_LIST_ERROR';

